# Generated by Django 3.0.4 on 2020-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time_completed',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='time_started',
            field=models.TimeField(null=True),
        ),
    ]
